gui/gui.pro
=> Fixes linking wrong qscintilla2 version - causing segfaults

languages/English.ts
Fixed a few spelling errors. Hopefully there won't be problems with line endings since I ran unix2dos on the file (you are developing this on Windows, right?).
=> Fixed spelling errors

languages/ChineseSimplified.ts
DO NOT MERGE BEFORE EVERY PROBLEM WAS SOLVED.
Refer #664 
C'est du chinois
=> Chinese Simplified Translation Add

languages/ChineseSimplified.ts
=> Correct the Chinese translation

languages/Russian.ts
All string were translated, many syntax and grammar errors were fixed.
=> Almost fully reworked and completed russian translation

CrashReporter/CrashReporter.pro, CrashReporter/languages/Spanish.ts, Grabber.pri, languages/Spanish.ts, release/languages/languages.ini, releases/setup.iss
Up-to-date spanish translation. :)
=> Add spanish translation

README.md
"shot list" caught my eye and then I found a couple other things to fix at the same time.
Failing `FileDownloaderTest`s can't be my fault, 'cause I didn't touch the code. :joy_cat:
=> README: Fix a couple typos & formatting things

_docs/filename.md
%all:ignorenamespace:character% -> %all:ignorenamespace=character%
=> Minor mistake in ignorenamespace (: instead of =)

scripts/build.sh
Change the job count to convention. (CPU threads +1)
No need for people who have more cores to have to wait or people with fewer cores to oversaturate.
=> Change job count.

src/languages/Korean.ts
I Started Korean translation after I knew this program was hosted in Github.
I'm about 40% done translating
=> Added Korean Translation

build.sh, scripts/build.sh
I have only lightly tested this since I don't actually have any use for it. It was just bugging me.
=> Build scripts to support multiple parameters, now quoted.

build.sh
The `build.sh` _Bash script_ has been modified to be able to comply with _Fedora_ requirements (_yum_).
This _Pull Request_ closes https://github.com/Bionus/imgbrd-grabber/issues/2339.
=> Add Fedora (yum) build

docs/_docs/filename.md
directory, old_directory and old_filename needed their place here, filename is already here and correct, so I just added the missings ones.
=> added missing tokens

README.md
I pushed a package on the AUR to build from the latest release on Github. Through this pull request I am merely adding details about it to make it easier for people using Arch based distributions to install it directly from the AUR.
=> Showing details about the AUR package on the project Readme.

src/gui/src/main-window.cpp, src/gui/src/settings/options-window.cpp, src/gui/src/viewer/zoom-window.cpp
Maybe fixed https://github.com/Bionus/imgbrd-grabber/issues/1864 Or not.
Three small fixes for things that kept grinding my gears for months.
Don't add me to any sort of contributors list, please. I don't need no reference.
=> Small bugfixes and features

src/lib/src/downloader/batch-downloader.cpp
that cast will fail if the first cast failed at line 110
=> dynamic cast

src/sites/NHentai/model.ts
Apparently, gif is supported by NH, so I added it to extensionMap here.
=> sites: nhentai: add gif to extensionMap

src/gui/src/main-window.cpp, src/gui/src/main-window.h, src/gui/src/main-window.ui, src/gui/src/tabs/search-tab.cpp, src/gui/src/tabs/search-tab.h, src/gui/src/tabs/tag-tab.ui
Proof of concept implementing feature #2607
=> Tab source pruning mockup

docs/docs/commands/danbooru.js
Adjusted the Danbooru.js script to work with a self-hosted instance on Unraid.
Also adjusted the rating to work by making them output the first letter in lower case which seems to be the accepted input as of now.
=> fix: Danbooru.js script adjustments

src/sites/NHentai/model.ts
Added .webp extension to Nhentai's model.ts extension map which fixes Issue #3322
=> Fix for issue #3322: .webp Support for Nhentai.net

src/gui/src/settings/options-window.cpp, src/lib/src/tags/tag-stylist.cpp, src/lib/tests/src/tags/tag-stylist-test.cpp
=> Clearer coloring for light and dark theme

.github/workflows/build.yml
It's a more recent LTS release of Ubuntu: 
https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_22.04_LTS_(Jammy_Jellyfish)
=> Update build.yml to `ubuntu-22.04`
