Bionus/imgbrd-grabber

- Grabber.pro
- release/Grabber.desktop
- source/functions.cpp
This commit sets up ```make install``` for linux and copies the default configs to /usr/local/Grabber/example where the user can ```cp /usr/local/Grabber/example/* ~/.Grabber/``` to get grabber running without all the files being in one directory. It also makes Grabber search for the ~/.Grabber directory Included is a Grabber.desktop file for linux desktop environments that support them.
> make install for linux

- Grabber.pro
- gui/gui.pro
used by setting the environment variable PREFIX when calling qmake Grabber.pro e.g.
```
$ qmake  PREFIX=/usr Grabber.pro
```
If PREFIX is not set it defaults to /usr/local
This can help automate creating distribution packages. I also plan on creating an aur package for Arch Linux, this should enable that.
> Linux installation prefix support

- src/mainwindow.cpp
This at least solves the issue, needExactTags should be moved out of filename and into another class due to it not being filename specific. needExactTags may also need to be modified to ensure that we are returning true on any possible situation that we may need to get all of the tags.
> Fix batches saving before their tags load ( Bionus/imgbrd-grabber#608 )

- Grabber.pri
- Grabber.pro
- tests/tests.pro
Commit 72624d49d3ddd5c9c1e05722d04c7e3f6f575daa broke the linux install scripts as it overwrote  the `PREFIX` variable that was passed to subprojects (`gui`, `tests`) with `PREFIX=\\\"$$(PREFIX)\\\"` which isn't a very valid path. This also fixes the problem of the icon not being copied to the `pixmaps` folder, as well as tests being installed.
> Fix linux install script

- CMakeLists.txt
Currently this will always use `/usr/local` so Grabber will not find sources when installed with a different prefix. Using this method when `-DCMAKE_INSTALL_PREFIX` is set it will use that prefix or the default from `CMAKE_INSTALL_PREFIX` (`/usr/local` on Linux and `C:\Program Files` on Windows)
> Fix prefix when looking for Grabber files on linux

- CMakeLists.txt
- lib/src/functions.cpp
Currently Grabber will check for the system settings file and folders which are only writable by root, this pull request changes Grabber to prefer settings files in the user's home directory if they exist so that changes may be saved.
> Prefer home folder over system folder settings

- tests/src/models/filename-test.cpp
Compiling fails with gcc on MAC OS 10.13.5, Fedora 28 and Debian 9
Builds now successful on Debian 9 and MAC OS. 
Fedora 28 is waiting to be confirmed
rel Issue:
https://github.com/Bionus/imgbrd-grabber/issues/1316
> Fix gcc compile errors on MAC OS and Debian 9

- cli/CMakeLists.txt
- cli/src/main.cpp
- lib/src/logger.cpp
- lib/src/logger.h
- lib/src/models/image.cpp
- lib/src/models/image.h
I made the grabber-cli capable of outputting json.
* `-d`
Sets loglevel to `Logger::Debug` and prints log to stdout, even without QT_DEBUG.
* __Image::parseDetails()__
logs `reply.error() != 0` as error, if it's not OperationCanceledError.
* **exit on error**
When using cli, the `Logger::log()` will throw if `Logger::Error` gets logged.
If wanted, errors can be ignored with the `--ignore-error` Option.
* `--no-login`
stops the automatic login attemp by using `site::setAutoLogin()`
* `--proxy`
sets proxy via `QNetworkProxy::setApplicationProxy`
* `-j`:
output all available details of all found images as json to stdout
* `--load-details`
When using `-j`, load details of every image. Uses asyncron requests.
* `--get-details <url-page>`
load details and print them as json
I wanted the cli to …
> Add features to the cli

- build-mac.sh
Building grabber requires node but it isn't installed with the macOS build script
> Added node to the mac build script

- lib/src/functions.cpp
This ensures a directory exists before settings files are copied to a writable location. Fixes #1761
> Use mkpath instead of mkdir to ensure path exists

- lib/src/functions.h
Properly fixes #1761 
With this change settings properly save for me and there are no errors about temp files in the log.
> Default writable to true so settings can be saved on Linux

- src/gui/src/ui/QBouton.cpp
The compilation kept failing, including the AUR imgbrd-grabber-git package. This fixes it.
> Added a missing include to fix compilation on Arch

- _docs/index.md
While attempting to browse the docs, I noticed some links were outdated/broken. This PR fixes some of the links on the **Getting Started** page.
Also, I reworded the **Linux Configuration** section slightly, and made minor edits elsewhere on the page, in an effort to make the documentation a little clearer.
> Fix broken links in Getting Started

- src/lib/src/functions.cpp
The temporary string object returned by the function call is
deallocated at the end of the expression. Since c_str() returns a
pointer to the internal string representation, the data is no longer
valid once the string object is destroyed. Due to this utime returns
ENOENT and Grabber prints an error in the log when modifying
file creation time.
Fixes https://github.com/Bionus/imgbrd-grabber/issues/2203
I don't think this issue affects Windows, since toWcharT is directly called on path variable. Maybe someone can check in Windows.
> Fix issue with dangling pointer when calling utime

- src/lib/src/auth/oauth2-auth.cpp
- src/lib/src/login/oauth2-login.cpp
- src/sites/Pixiv/model.ts
- src/sites/types.d.ts
This is a quick (and might dirty) fix for pixiv login,
which is a workaround suggested in pixivpy[\[^1\]][1].
This PR do:
* add an oauth type "refresh_token" which simply use user-supplied tokens to authenticate,
* some UI modifications that allow user to set access_token and refresh_token,
* set pixiv's oauth type to refresh_token.
[1]: https://github.com/upbit/pixivpy/blob/master/pixivpy3/api.py#L81
> Fix for pixiv login

- src/gui/src/main-window.cpp
- src/gui/src/settings/options-window.cpp
- src/gui/src/settings/options-window.ui
- src/gui/src/viewer/zoom-window.cpp
- src/lib/src/functions.cpp
- src/lib/src/functions.h
I tried squashing the old script stuff. Hopefully this is slightly more convenient for you. I will probably make the other shortcuts customisable too. Does this seem like a good idea?
The reasons why I changed the default shortcuts, aside from my personal preference, are:
1. Not requiring multiple modifiers for basic actions.
2. Making all shortcuts (except left/right navigation) operable with left hand, so people don't have to move their hand off their mouse to use them.
3. Making the shortcuts more consistent/reliable (see below). These might be my fault somehow but replacing them fixed it so I don't think so.
QKeySequence::SaveAs is empty on my system. Unreliable.
QKeySequence::Save is 5 on my system for keyViewerSave. Doesn't make sense.
QKeySequence::Save is empty on my system for …
> Customisable Shortcuts

- src/gui/src/helpers.cpp
- src/gui/src/helpers.h
- src/gui/src/main-window.cpp
- src/gui/src/settings/options-window.cpp
- src/gui/src/settings/options-window.ui
- src/gui/src/settings/start-window.cpp
- src/gui/src/viewer/details-window.cpp
- src/gui/src/viewer/zoom-window.cpp
I think this works but some of the dialogues are called from functions in "options-window.cpp". The problem(s) with that are:
1. QShortcut would need to be included (I think). Easy to fix but I don't know if you think it's worth the extra code.
2. Some of those functions don't have a pointer to the settings they would reference. I assume it's a bad idea to reference m_profile->getSettings() each time. Other options I can think of would be storing a pointer to settings in the class instance or passing the pointer into those functions as a parameter.
Adding support for FilenameWindow would also require including QShortcut, either in "start-window.cpp" or in "filename-window.cpp". Again, not sure if it's worth the extra code.
> Adding shortcuts for miscellaneous dialogues.

- build.sh
QtNetworkAuth is a new dependency added within the past few versions of Grabber or reorganisation of Gentoo packages. I noticed that something on my system had already pulled in qtnetwork-- I have not tested to confirm that it is required, but it seems very likely.
> Added dependencies.

- docs/_docs/commands/danbooru.md
`%path:nobackslash%` makes sure the path is passed correctly for users who use subfolders.
> Fix "nod danbooru.js" command

- build.sh
I've added qt5-qtnetworkauth-devel to the Yum install list because the build fails on Fedora if qt5-qtnetworkauth-devel is not installed.
> Add qt5-qtnetworkauth-devel to Yum install

- build.sh
Added libqt5networkauth5-dev to the apt-get requirements because the build fails on Debian based distros without it installed
> Add libqt5networkauth5-dev to apt-get requirements

- src/sites/Twitter/model.ts
- src/sites/package-lock.json
- src/sites/package.json
It catches one new error: `parseTweet` can never return a boolean or even a falsy value AFAICT.
> Update TypesScript to 4.9.3.

- docs/_docs/commands/szurubooru.js
Fix for "sensitive" images being skipped from being uploaded. Also included additional redundant categories as catch-alls so that nothing is missed.
> Fix sensitive images being skipped

- docs/_docs/commands/szurubooru.js
Fixed `getTag()` for tags that contained a "?" or "\\"
> Encode getTag URI

- src/lib/src/external/exiftool.cpp
https://github.com/Bionus/imgbrd-grabber/issues/3213
> fix: ignore minor Exiftool errors to allow writing to JXL (fix #3213)

- src/gui/CMakeLists.txt
You need to specify NetworkAuth in the dependencies to fix this error https://github.com/Bionus/imgbrd-grabber/issues/3258 on build. I also encountered this in an unstable version of nixpkgs.
> fix: add NetworkAuth dependency in gui for correct build
